### PR TITLE
Upgrade to Gym 0.21

### PR DESCRIPTION
**Pull request by AdamGleave**
Same methodology as https://github.com/Stable-Baselines-Team/rl-colab-notebooks/pull/7 -- searched for environment names, changed `Pendulum-v0` to `Pendulum-v1`, tested those two notebooks that were changed still run OK.

### CODE REVIEW

**Comment by AdamGleave** [comment]
I ran into a few indenting issues when running these notebooks, I'm guessing this is a Colab vs Jupyter incompatibility. I didn't fix that in the commit for fear of breaking it on Colab.

**Comment by araffin** [comment]
> I ran into a few indenting issues when running these notebooks, I'm guessing this is a Colab vs Jupyter incompatibility. I didn't fix that in the commit for fear of breaking it on Colab.

There is actually an issue with the 4th notebook for the `PlottingCallback`.

The rest is ready (I tested it) when SB3 1.5.0 will be released (with support for gym 0.21).

**Comment by araffin** [comment]
The indentation bug was introduced in ac1e714c75084517767d4524e1b0a44222281495 when refactoring callbacks, will push a fix

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
