### PR TITLE
Update to gym 0.26

### PR DESCRIPTION
**Pull request by arjun-kg**
Notebooks checked with SB3 at the current state of PR - https://github.com/DLR-RM/stable-baselines3/pull/780 
To be merged only after next SB3 release that uses gym 0.23.1. 

1. Tiny change with seed being set in env.reset() instead of env.seed() to suppress a deprecation warning. 
2. Fixed typos with `codespell`.
3. Left an existing Monitor wrapper warning alone (when eval env is not wrapper with Monitor) since it's a simple example.

### CODE REVIEW

**Review by araffin — APPROVED** [review]
LGTM, thanks =) will merge once new SB3 version is released

and thanks for the typo correction!

**Comment by tlpss** [comment]
@araffin the first tutorial is not yet updated as it depends on the VideoRecorder. Furthermore I'm not sure if it is always clear that gym has a new API but that SB3 still uses the old API for it's VecEnv (could be confusing). 

Also VScode appears to change a whole lot of meta data, not sure how to fix that though.

**Comment by araffin** [comment]
> Furthermore I'm not sure if it is always clear that gym has a new API but that SB3 still uses the old API for it's VecEnv (could be confusing).

I see. Well, SB3 VecEnv uses its own API, the input/outputs/behavior are anyway different from single gym Env.
It should be ok as long as we explicitly mention when we use vec env or not.

Tell me if there are specific parts that I should take a look at.

> Also VScode appears to change a whole lot of meta data, not sure how to fix that though.

no worry about that, I'll probably clean that up when I'll try the notebooks on colab

**Comment by araffin** [comment]
> first tutorial is not yet updated as it depends on the VideoRecorder.

@tlpss could you work on that?

**Comment by tlpss** [comment]
> @tlpss could you work on that?

Yes, will take a look in the next days!

**Comment by araffin** [comment]
> Yes, will take a look in the next days!

I actually made recording video work in https://github.com/DLR-RM/rl-baselines3-zoo/pull/256, so it might work now.

**Comment by tlpss** [comment]
> > Yes, will take a look in the next days!
> 
> I actually made recording video work in [DLR-RM/rl-baselines3-zoo#256](https://github.com/DLR-RM/rl-baselines3-zoo/pull/256), so it might work now.

I'm waiting for the render API changes to get merged, to make sure it will work on the lastest VecEnv api

**Comment by araffin** [comment]
I think that the only thing missing is testing in google colab + pointing to the doc for gym API vs VecEnv API

**Pull request merged**
